# config.yaml
server:
  host: 0.0.0.0
  port: 8000

models:
  llama2-7b:
    type: llama.cpp

  gpt-3.5-turbo-proxy:
    type: openai_proxy
    api_key: sk-
    base_url: https://api.openai.com/v1
    model: gpt-3.5-turbo

  deepseek-r1:
    type: openai_proxy
    api_key: sk-
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: deepseek-r1

  qwen2.5-0.5b:
    type: tcp_client
    host: "192.168.20.183" 
    port: 10001
    model_name: "qwen2.5-0.5B-prefill-20e"
    object: "llm.setup"
    pool_size: 2
    response_format: "llm.utf-8.stream"
    input: "llm.utf-8"
    system_prompt: |
      You are a helpful assistant. 

  Qwen2.5-0.5B-w8a16:
    type: tcp_client
    host: "192.168.20.183"
    port: 10001
    model_name: "Qwen2.5-0.5B-w8a16"
    object: "llm.setup"
    pool_size: 2
    response_format: "llm.utf-8.stream"
    input: "llm.utf-8"
    system_prompt: |
      You are a helpful assistant.

  deepseek-r1-1.5B-ax630c:
    type: tcp_client
    host: "192.168.20.183"
    port: 10001
    model_name: "deepseek-r1-1.5B-ax630c"
    object: "llm.setup"
    pool_size: 1
    response_format: "llm.utf-8.stream"
    input: "llm.utf-8"
    system_prompt: |
      You are a helpful assistant.

  internvl2.5-1B-ax630c:
    type: tcp_client
    host: "192.168.20.183"
    port: 10001
    model_name: "internvl2.5-1B-ax630c"
    object: "vlm.setup"
    pool_size: 1
    response_format: "vlm.utf-8.stream"
    input: "vlm.utf-8"
    system_prompt: |
      You are a helpful assistant.

  qwen-vl-plus:
    type: vision_model
    api_key: sk-
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen-vl-plus
    max_image_size: 4194304
    image_timeout: 20

  melotts:
    type: tts
    host: "192.168.20.183"
    port: 10001
    model_name: "melotts_zh-cn"
    object: "melotts.setup"
    response_format: "wav.base64"
    input: "tts.utf-8"

  whisper:
    type: asr
    host: "192.168.20.183"
    port: 10001
    model_name: "whisper-tiny"
    object: "whisper.setup"
    response_format: "asr.utf-8"
    input: "whisper-tiny"
    language: "en"